//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trackit.App.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ActivityEditViewTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActivityEditViewTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trackit.App.Resources.Texts.ActivityEditViewTexts", typeof(ActivityEditViewTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new activity.
        /// </summary>
        public static string Activity_Edit_Text {
            get {
                return ResourceManager.GetString("Activity_Edit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the description.
        /// </summary>
        public static string Description_Input_Text {
            get {
                return ResourceManager.GetString("Description_Input_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Description_Label_Text {
            get {
                return ResourceManager.GetString("Description_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        public static string From_Label_Text {
            get {
                return ResourceManager.GetString("From_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the name of the activity.
        /// </summary>
        public static string Name_Input_Text {
            get {
                return ResourceManager.GetString("Name_Input_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name_Label_Text {
            get {
                return ResourceManager.GetString("Name_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project:.
        /// </summary>
        public static string Project_Label_Text {
            get {
                return ResourceManager.GetString("Project_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save_Button_Text {
            get {
                return ResourceManager.GetString("Save_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string To_Label_Text {
            get {
                return ResourceManager.GetString("To_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string Type_Label_Text {
            get {
                return ResourceManager.GetString("Type_Label_Text", resourceCulture);
            }
        }
    }
}
