//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trackit.App.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ActivityEditViewModelTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActivityEditViewModelTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trackit.App.Resources.Texts.ActivityEditViewModelTexts", typeof(ActivityEditViewModelTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity needs to start before it ends.
        /// </summary>
        public static string Invalid_Date_Message {
            get {
                return ResourceManager.GetString("Invalid_Date_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date combination.
        /// </summary>
        public static string Invalid_Date_Title {
            get {
                return ResourceManager.GetString("Invalid_Date_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the activity needs to be filled.
        /// </summary>
        public static string Missing_Fields_Message_Name {
            get {
                return ResourceManager.GetString("Missing_Fields_Message_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity has to belong to a project.
        /// </summary>
        public static string Missing_Fields_Message_Project {
            get {
                return ResourceManager.GetString("Missing_Fields_Message_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field empty.
        /// </summary>
        public static string Missing_Fields_Title {
            get {
                return ResourceManager.GetString("Missing_Fields_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity overlaps with user&apos;s other activities.
        /// </summary>
        public static string OverlapError_Alert_Message {
            get {
                return ResourceManager.GetString("OverlapError_Alert_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertion error.
        /// </summary>
        public static string OverlapError_Alert_Title {
            get {
                return ResourceManager.GetString("OverlapError_Alert_Title", resourceCulture);
            }
        }
    }
}
